[theme]
primaryColor = "#00d9ff"
backgroundColor = "#1e293b"
secondaryBackgroundColor = "#475569"
textColor = "#f1f5f9"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200

[browser]
gatherUsageStats = false

[client]
showErrorDetails = true
toolbarMode = "minimal"
