[theme]
primaryColor = "#00f5ff"
backgroundColor = "#0a0e27"
secondaryBackgroundColor = "#141b2d"
textColor = "#ffffff"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200

[browser]
gatherUsageStats = false

[client]
showErrorDetails = true
toolbarMode = "minimal"
